spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/livraria
spring.datasource.username=postgres
spring.datasource.password=SENHA_AQUI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true